config/routes.rb
STV3::Application.routes.draw do

  # -------------------------------------------------------
  # default route to the region index page
  root :to => 'regions#index'

  # -------------------------------------------------------
  # static pages of supporting information
  match 'About'    => 'pages#about'
  match 'Login'    => 'pages#login'
  match 'Dashboard'=> 'pages#dashboard'
  match 'Privacy'  => 'pages#privacy'
  match 'Contact'  => 'pages#contact'
  
  # -------------------------------------------------------
  # specific resource routes
  resources :regions, :only => [:index, :show]
  resources :programs
  resources :rules
  resources :sports, :only => [:show]
  resources :channels, :only => [:index, :show]
  #resources :log_entries
  #resources :raw_channels 
  #resources :raw_programs
  
  # -------------------------------------------------------
  # special routes - these need to be last // catch all
  
  # special routes for /region
  match ':id' => 'regions#show'
    
  # special route for /region/sport
  match ':region/:sport' => 'programs#index'

end

app/models/channel.rb
class Channel < ActiveRecord::Base
   
  has_many :programs
  
  extend FriendlyId
  friendly_id :channel_name, use: :slugged
  
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  
  before_filter :authenticate
  
  # GET /channels
  # GET /channels.json
  def index
    @channels = Channel.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @channels }
    end
  end

  # GET /channels/1
  # GET /channels/1.json
  def show
    @channel = Channel.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @channel }
    end
  end

  # GET /channels/new
  # GET /channels/new.json
  def new
    @channel = Channel.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @channel }
    end
  end

  # GET /channels/1/edit
  def edit
    @channel = Channel.find(params[:id])
  end

  # POST /channels
  # POST /channels.json
  def create
    @channel = Channel.new(params[:channel])

    respond_to do |format|
      if @channel.save
        format.html { redirect_to @channel, notice: 'Channel was successfully created.' }
        format.json { render json: @channel, status: :created, location: @channel }
      else
        format.html { render action: "new" }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /channels/1
  # PUT /channels/1.json
  def update
    @channel = Channel.find(params[:id])

    respond_to do |format|
      if @channel.update_attributes(params[:channel])
        format.html { redirect_to @channel, notice: 'Channel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1
  # DELETE /channels/1.json
  def destroy
    @channel = Channel.find(params[:id])
    @channel.destroy

    respond_to do |format|
      format.html { redirect_to channels_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/views/channels/_form.html.erb
<%= form_for(@channel) do |f| %>
  <% if @channel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@channel.errors.count, "error") %> prohibited this channel from being saved:</h2>

      <ul>
      <% @channel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :xmltv_id %><br />
    <%= f.text_field :xmltv_id %>
  </div>
  <div class="field">
    <%= f.label :channel_name %><br />
    <%= f.text_field :channel_name %>
  </div>
  <div class="field">
    <%= f.label :channel_short_name %><br />
    <%= f.text_field :channel_short_name %>
  </div>
  <div class="field">
    <%= f.label :channel_logo_url %><br />
    <%= f.text_field :channel_logo_url %>
  </div>
  <div class="field">
    <%= f.label :channel_free_or_pay %><br />
    <%= f.text_field :channel_free_or_pay %>
  </div>
  <div class="field">
    <%= f.label :slug %><br />
    <%= f.text_field :slug %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/channels/edit.html.erb
<h1>Editing channel</h1>

<%= render 'form' %>

<%= link_to 'Show', @channel %> |
<%= link_to 'Back', channels_path %>

app/views/channels/index.html.erb
<h1>Listing channels</h1>

<table>
  <tr>
    <th>Xmltv</th>
    <th>Channel name</th>
    <th>Channel short name</th>
    <th>Channel logo url</th>
    <th>Channel free or pay</th>
    <th>Slug</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @channels.each do |channel| %>
  <tr>
    <td><%= channel.xmltv_id %></td>
    <td><%= channel.channel_name %></td>
    <td><%= channel.channel_short_name %></td>
    <td><%= channel.channel_logo_url %></td>
    <td><%= channel.channel_free_or_pay %></td>
    <td><%= channel.slug %></td>
    <td><%= link_to 'Show', channel %></td>
    <td><%= link_to 'Edit', edit_channel_path(channel) %></td>
    <td><%= link_to 'Destroy', channel, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Channel', new_channel_path %>

app/views/channels/new.html.erb
<h1>New channel</h1>

<%= render 'form' %>

<%= link_to 'Back', channels_path %>

app/views/channels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Xmltv:</b>
  <%= @channel.xmltv_id %>
</p>

<p>
  <b>Channel name:</b>
  <%= @channel.channel_name %>
</p>

<p>
  <b>Channel short name:</b>
  <%= @channel.channel_short_name %>
</p>

<p>
  <b>Channel logo url:</b>
  <%= @channel.channel_logo_url %>
</p>

<p>
  <b>Channel free or pay:</b>
  <%= @channel.channel_free_or_pay %>
</p>

<p>
  <b>Slug:</b>
  <%= @channel.slug %>
</p>


<%= link_to 'Edit', edit_channel_path(@channel) %> |
<%= link_to 'Back', channels_path %>