config/routes.rb
STV3::Application.routes.draw do

  # -------------------------------------------------------
  # default route to the region index page
  root :to => 'regions#index'

  # -------------------------------------------------------
  # static pages of supporting information
  match 'About'    => 'pages#about'
  match 'Login'    => 'pages#login'
  match 'Dashboard'=> 'pages#dashboard'
  match 'Privacy'  => 'pages#privacy'
  match 'Contact'  => 'pages#contact'
  
  # -------------------------------------------------------
  # specific resource routes
  resources :regions, :only => [:index, :show]
  resources :programs
  resources :rules
  resources :sports, :only => [:show]
  resources :channels, :only => [:index, :show]
  #resources :log_entries
  #resources :raw_channels 
  #resources :raw_programs
  
  # -------------------------------------------------------
  # special routes - these need to be last // catch all
  
  # special routes for /region
  match ':id' => 'regions#show'
    
  # special route for /region/sport
  match ':region/:sport' => 'programs#index'

end

app/models/program.rb
class Program < ActiveRecord::Base
  
  belongs_to :channel
  belongs_to :sport
  belongs_to :region
  
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  # GET /programs
  # GET /programs.json
  def index
    
    @region = Region.find_by_region_name(params[:region])
    @sport = Sport.find_by_sport_name(params[:sport])
    
    querystring = "
    SELECT DISTINCT programs.title, programs.subtitle, programs.sport_name, channels.channel_name, channels.channel_short_name,
           DATE_FORMAT(programs.start_datetime,'%a, %d %b %Y') AS start_day, programs.start_datetime,
           programs.end_datetime, DATE_FORMAT(programs.start_datetime,'%k:%i') AS start_time,
           DATE_FORMAT(programs.end_datetime,'%k:%i') AS end_time
    FROM programs
    LEFT JOIN channels 
    ON programs.channel_id = channels.id
    WHERE programs.end_datetime >= NOW()
    AND programs.region_name = '#{params[:region]}'
    AND programs.sport_name = '#{params[:sport]}'
    ORDER BY start_datetime ASC, end_datetime ASC, channel_name ASC, subtitle DESC, title DESC
    "  
    @current_programs = Region.find_by_sql(querystring)
      
    @title = "#{@sport.sport_name} on Television in #{@region.region_name}, Australia"
    @meta_keywords = "sport, television, tv, coverage, tonight, Australia, Melbourne, Sydney, Brisbane, Adalaide, Perth"
    @meta_description = "Your source for sport on television in #{@region.region_name}, Australia.  Find out when sport is on Free-to-air or Pay TV.  Watch live sport on TV tonight." 
      
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @programs }
    end
  end


  # GET /programs/1
  # GET /programs/1.json
  def show
    @program = Program.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @program }
    end
  end

  # GET /programs/new
  # GET /programs/new.json
  def new
    @program = Program.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @program }
    end
  end

  # GET /programs/1/edit
  def edit
    @program = Program.find(params[:id])
  end

  # POST /programs
  # POST /programs.json
  def create
    @program = Program.new(params[:program])

    respond_to do |format|
      if @program.save
        format.html { redirect_to @program, notice: 'Program was successfully created.' }
        format.json { render json: @program, status: :created, location: @program }
      else
        format.html { render action: "new" }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /programs/1
  # PUT /programs/1.json
  def update
    @program = Program.find(params[:id])

    respond_to do |format|
      if @program.update_attributes(params[:program])
        format.html { redirect_to @program, notice: 'Program was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program = Program.find(params[:id])
    @program.destroy

    respond_to do |format|
      format.html { redirect_to programs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/programs/_form.html.erb
<%= form_for(@program) do |f| %>
  <% if @program.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@program.errors.count, "error") %> prohibited this program from being saved:</h2>

      <ul>
      <% @program.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :subtitle %><br />
    <%= f.text_field :subtitle %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :start_datetime %><br />
    <%= f.datetime_select :start_datetime %>
  </div>
  <div class="field">
    <%= f.label :end_datetime %><br />
    <%= f.datetime_select :end_datetime %>
  </div>
  <div class="field">
    <%= f.label :region_name %><br />
    <%= f.text_field :region_name %>
  </div>
  <div class="field">
    <%= f.label :region_id %><br />
    <%= f.number_field :region_id %>
  </div>
  <div class="field">
    <%= f.label :sport_name %><br />
    <%= f.text_field :sport_name %>
  </div>
  <div class="field">
    <%= f.label :sport_id %><br />
    <%= f.number_field :sport_id %>
  </div>
  <div class="field">
    <%= f.label :channel_xmltv_id %><br />
    <%= f.text_field :channel_xmltv_id %>
  </div>
  <div class="field">
    <%= f.label :channel_id %><br />
    <%= f.number_field :channel_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/programs/edit.html.erb
<h1>Editing program</h1>

<%= render 'form' %>

<%= link_to 'Show', @program %> |
<%= link_to 'Back', programs_path %>

app/views/programs/index.html.erb
<% last_program = nil %>
<% day_count = 0 %>
<% @current_programs.each do |program| %>
<% if !last_program.nil? && program.start_day != last_program.start_day %>
        </td>
      </tr>
    </tbody>
  </table>
<% end %>
<% if last_program.nil? || program.start_day != last_program.start_day %>
  <% if day_count == 2 || day_count == 5 || day_count == 8 %>
  <p class="centre advertisment"><small>Advertisment</small></p>
  <img src="http://placehold.it/728x90" alt="placeholder 728x90">
  <% end %>  
  <table class="program">
    <colgroup>
      <col class="col_time">
      <col class="col_title">
      <col class="col_sport">
      <col class="col_channel">
    </colgroup>
    <tbody>
      <tr>
       <td class="program_header" colspan="4"><%= program.start_day %></td>
      </tr>
      <tr>
        <th class="program_header">Time</th> 
        <th class="program_header">Title</th>
        <th class="program_header">Sport</th>
        <th class="program_header">Channel</th>
      </tr>
      <tr class="program">
        <td class="program"><%= program.start_time %></td>
        <td class="program"><%= program.title %><% if program.subtitle != "" %><%=" ("+program.subtitle+")"%><% end %></td>
        <td class="program"><%= program.sport_name %></td>
        <td class="program"><%= program.channel_name %> (<%= program.start_time %> to <%= program.end_time %>)
<% day_count = day_count + 1 %>
<% else %>
<% if program.sport_name == last_program.sport_name && program.channel_short_name == last_program.channel_short_name && (program.start_datetime == last_program.start_datetime || program.end_datetime == last_program.end_datetime) %>
       <% if program.channel_name != last_program.channel_name %><br><%=program.channel_name%> (<%=program.start_time%> to <%=program.end_time%>)<% end %>          
<% else %>
        </td>
      </tr>
      <tr class="program">
        <td class="program"><%= program.start_time %></td>
        <td class="program"><%= program.title %><% if program.subtitle != "" %><%=" ("+program.subtitle+")"%><% end %></td>
        <td class="program"><%= program.sport_name %></td>
        <td class="program"><%= program.channel_name %> (<%= program.start_time %> to <%= program.end_time %>)
<% end %>
<% end %>  
<% last_program = program %>
<% end %>
        </td>
      </tr>
    </tbody>
  </table>

app/views/programs/new.html.erb
<h1>New program</h1>

<%= render 'form' %>

<%= link_to 'Back', programs_path %>

app/views/programs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @program.title %>
</p>

<p>
  <b>Subtitle:</b>
  <%= @program.subtitle %>
</p>

<p>
  <b>Category:</b>
  <%= @program.category %>
</p>

<p>
  <b>Description:</b>
  <%= @program.description %>
</p>

<p>
  <b>Start datetime:</b>
  <%= @program.start_datetime %>
</p>

<p>
  <b>End datetime:</b>
  <%= @program.end_datetime %>
</p>

<p>
  <b>Region name:</b>
  <%= @program.region_name %>
</p>

<p>
  <b>Region:</b>
  <%= @program.region_id %>
</p>

<p>
  <b>Sport name:</b>
  <%= @program.sport_name %>
</p>

<p>
  <b>Sport:</b>
  <%= @program.sport_id %>
</p>

<p>
  <b>Channel xmltv:</b>
  <%= @program.channel_xmltv_id %>
</p>

<p>
  <b>Channel:</b>
  <%= @program.channel_id %>
</p>


<%= link_to 'Edit', edit_program_path(@program) %> |
<%= link_to 'Back', programs_path %>