config/routes.rb
STV3::Application.routes.draw do

  # -------------------------------------------------------
  # default route to the region index page
  root :to => 'regions#index'

  # -------------------------------------------------------
  # static pages of supporting information
  match 'About'    => 'pages#about'
  match 'Login'    => 'pages#login'
  match 'Dashboard'=> 'pages#dashboard'
  match 'Privacy'  => 'pages#privacy'
  match 'Contact'  => 'pages#contact'
  
  # -------------------------------------------------------
  # specific resource routes
  resources :regions, :only => [:index, :show]
  resources :programs
  resources :rules
  resources :sports, :only => [:show]
  resources :channels, :only => [:index, :show]
  #resources :log_entries
  #resources :raw_channels 
  #resources :raw_programs
  
  # -------------------------------------------------------
  # special routes - these need to be last // catch all
  
  # special routes for /region
  match ':id' => 'regions#show'
    
  # special route for /region/sport
  match ':region/:sport' => 'programs#index'

end

app/models/channel.rb
class Channel < ActiveRecord::Base
   
  has_many :programs
  
  extend FriendlyId
  friendly_id :channel_name, use: :slugged
  
end

app/models/log_entry.rb
class LogEntry < ActiveRecord::Base
end

app/models/parameter.rb
class Parameter < ActiveRecord::Base
end

app/models/program.rb
class Program < ActiveRecord::Base
  
  belongs_to :channel
  belongs_to :sport
  belongs_to :region
  
end

app/models/raw_channel.rb
class RawChannel < ActiveRecord::Base
end

app/models/raw_program.rb
class RawProgram < ActiveRecord::Base
end

app/models/region.rb
class Region < ActiveRecord::Base
  
  has_many :programs
  
  extend FriendlyId
  friendly_id :region_name, use: :slugged
  
end

app/models/rule.rb
class Rule < ActiveRecord::Base
end

app/models/sport.rb
class Sport < ActiveRecord::Base
  
  has_many :programs
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def logged_in?
    not request.authorization.nil?
  end
    
  def google_analytics
    google_code ="
    <script>
    var _gaq=[['_setAccount','UA-00000000-1'],['_trackPageview']];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
    g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g,s)}(document,'script'));
    </script>"
       
    google_code
  end
  
  
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/log_entries_helper.rb
module LogEntriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/parameters_helper.rb
module ParametersHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/raw_channels_helper.rb
module RawChannelsHelper
end

app/helpers/raw_programs_helper.rb
module RawProgramsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/views/shared/_footer_page_list.html.erb
                        <ul class="footer_nav">
                          <h4>Pages</h4>
                          <li><a href="/">Home</a></li>
                          <li><a href="/About">About</a></li>
                          <li><a href="/Contact">Contact</a></li>
                          <li><a href="/Privacy">Privacy</a></li>
                          <li><a href="/Login">Login</a></li> 
                        </ul>

app/views/shared/_footer_region_list.html.erb
                        <% if !@regions.nil? %>
                        <ul class="footer_nav">
                          <h4>Select Region</h4>
                          <% @regions.each do |region| %>
                          <li><%= link_to region.region_name, "/"+region.region_name+"/" %></li>
                          <% end %>
                        </ul>
                        <% end %>

app/views/shared/_footer_social_list.html.erb
                        <ul class="footer_nav">
                          <h4>Get Social</h4>
                          <li><a href="/Email"><%= image_tag "icons/32x32/email.png" %></a></li>
                          <li><a href="/Facebook"><%= image_tag "icons/32x32/facebook.png" %></a></li>
                          <li><a href="/Twitter"><%= image_tag "icons/32x32/twitter.png" %></a></li> 
                        </ul>

app/views/shared/_left_menu_advertisment1.html.erb
<div class="left_advertisment">
  <p class="centre advertisment"><small>Advertisment</small></p>
  <img src="http://placehold.it/200x200" alt="placeholder 200x200">
</div>

app/views/shared/_left_menu_advertisment2.html.erb
<div class="left_advertisment">
  <p class="centre advertisment"><small>Advertisment</small></p>
  <img src="http://placehold.it/200x200" alt="placeholder 200x200">
</div>

app/views/shared/_left_menu_bottom.html.erb
<div class="left_bottom">
  
</div>

app/views/shared/_left_menu_logged_in.html.erb
<% if logged_in? %>
  <div class="left_logged_in">
    <div class="alert alert-success centre">
      <i class="icon-user"></i> You are logged in!
    </div>
    <ul>
      <h3>Admin Options</h3>
      <li><a href="/Login">Login</a></li>
      <li><a href="/Dashboard">Dashboard</a></li>
      <li><%=link_to("Rules", rules_path) %></li>
      <li><%=link_to("Channels", channels_path) %></li>
      
    </ul>
  </div>
<% end %>   

app/views/shared/_left_menu_news_feed.html.erb
<% if !@news_entries.nil? %>
  <div class="left_news_feed">
    <ul>
      <h3>Latest News</h3>
      <% @news_entries.each do |news_entry| %>
      <li><%= link_to news_entry.title, news_entry.url %> <%= news_entry.summary %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_left_menu_page_list.html.erb
<div class="left_page_list">
  <ul>
    <h3>Pages</h3>
    <li><a href="/">Home</a></li>
    <li><a href="/About">About</a></li>
    <li><a href="/Contact">Contact</a></li>
    <li><a href="/Privacy">Privacy</a></li>
    <li><a href="/Login">Login</a></li>
  </ul>
</div>

app/views/shared/_left_menu_region_list.html.erb
<% if !@regions.nil? %>
  <div class="left_region_list">
    <ul>
      <h3>Select Region</h3>
      <% @regions.each do |region| %>
      <li>
        <%= link_to region.region_name, "/"+region.region_name+"/" %>
        <% if logged_in? %>
          <%= link_to "<i class=\"icon-edit\"></i>".html_safe, region_path(region)  %>
        <% end %>
      </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_left_menu_sport_list.html.erb
<% if !@sports.nil? && !@region.nil? %>
  <div class="left_sport_list">
    <ul>
      <h3>Select Sport</h3>
      <% @sports.each do |sport| %>
      <li>       
        <%= link_to sport.sport_name, "/"+@region.region_name+"/"+sport.sport_name+"/" %>
        <% if logged_in? %>
          <%= link_to "<i class=\"icon-edit\"></i>".html_safe, sport_path(sport)  %>
        <% end %>
      </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_main_breadcrumbs.html.erb
<ul class="breadcrumb">
  <li>
    <a href="/">SPORT ON TV</a>
    <span class="divider">/</span>
  </li>
  <% if !@breadcrumb.nil? %>
    <li class="active">
    <%= @breadcrumb %>
  </li>
  <% elsif !@region.nil? && @sport.nil? %>
  <li class="active">
    <%= @region.region_name %>
  </li>
  <% elsif !@sport.nil? %>
  <li>
    <%= link_to @region.region_name, "/"+@region.region_name+"/" %>
    <span class="divider">/</span>
  </li>
  <li class="active">
    <%= @sport.sport_name %>
  </li>
  <% end %>
</ul>

app/views/shared/_right_render.html.erb
<div class="right_yield">
  <%= render "shared/main_breadcrumbs" %>    
  <%= yield %>
</div>