config/routes.rb
STV3::Application.routes.draw do

  # -------------------------------------------------------
  # default route to the region index page
  root :to => 'regions#index'

  # -------------------------------------------------------
  # static pages of supporting information
  match 'About'    => 'pages#about'
  match 'Login'    => 'pages#login'
  match 'Dashboard'=> 'pages#dashboard'
  match 'Privacy'  => 'pages#privacy'
  match 'Contact'  => 'pages#contact'
  
  # -------------------------------------------------------
  # specific resource routes
  resources :regions, :only => [:index, :show]
  resources :programs
  resources :rules
  resources :sports, :only => [:show]
  resources :channels, :only => [:index, :show]
  #resources :log_entries
  #resources :raw_channels 
  #resources :raw_programs
  
  # -------------------------------------------------------
  # special routes - these need to be last // catch all
  
  # special routes for /region
  match ':id' => 'regions#show'
    
  # special route for /region/sport
  match ':region/:sport' => 'programs#index'

end

app/models/channel.rb
class Channel < ActiveRecord::Base
   
  has_many :programs
  
  extend FriendlyId
  friendly_id :channel_name, use: :slugged
  
end

app/models/log_entry.rb
class LogEntry < ActiveRecord::Base
end

app/models/parameter.rb
class Parameter < ActiveRecord::Base
end

app/models/program.rb
class Program < ActiveRecord::Base
  
  belongs_to :channel
  belongs_to :sport
  belongs_to :region
  
end

app/models/raw_channel.rb
class RawChannel < ActiveRecord::Base
end

app/models/raw_program.rb
class RawProgram < ActiveRecord::Base
end

app/models/region.rb
class Region < ActiveRecord::Base
  
  has_many :programs
  
  extend FriendlyId
  friendly_id :region_name, use: :slugged
  
end

app/models/rule.rb
class Rule < ActiveRecord::Base
end

app/models/sport.rb
class Sport < ActiveRecord::Base
  
  has_many :programs
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  before_filter :authenticate, :except => [:about, :privacy, :contact]
    
  def about
    @title = "About | Sport on Television in Australia"
    @breadcrumb = "About"
    @meta_keywords = "sport, television, tv, coverage, tonight, Australia, Melbourne, Sydney, Brisbane, Adalaide, Perth"
    @meta_description = "Your source for sport on television in Australia.  Find out when sport is on Free-to-air or Pay TV.  Watch live sport on TV tonight."
    
  end

  def privacy
    @title = "Privacy Statement | Sport on Television in Australia"
    @breadcrumb = "Privacy"
    @meta_keywords = "sport, television, tv, coverage, tonight, Australia, Melbourne, Sydney, Brisbane, Adalaide, Perth"
    @meta_description = "Your source for sport on television in Australia.  Find out when sport is on Free-to-air or Pay TV.  Watch live sport on TV tonight."
    
  end

  def contact
    @title = "Contact Us | Sport on Television in Australia"
    @breadcrumb = "Contact"
    @meta_keywords = "sport, television, tv, coverage, tonight, Australia, Melbourne, Sydney, Brisbane, Adalaide, Perth"
    @meta_description = "Your source for sport on television in Australia.  Find out when sport is on Free-to-air or Pay TV.  Watch live sport on TV tonight."
        
  end
  
  def login
    @title = "Login | Sport on Television in Australia"
    @breadcrumb = "Login"
    @meta_keywords = "sport, television, tv, coverage, tonight, Australia, Melbourne, Sydney, Brisbane, Adalaide, Perth"
    @meta_description = "Your source for sport on television in Australia.  Find out when sport is on Free-to-air or Pay TV.  Watch live sport on TV tonight."
       
  end
  
  def dashboard
    @title = "Dashboard | Sport on Television in Australia"
    @breadcrumb = "Dashboard"
    @meta_keywords = "sport, television, tv, coverage, tonight, Australia, Melbourne, Sydney, Brisbane, Adalaide, Perth"
    @meta_description = "Your source for sport on television in Australia.  Find out when sport is on Free-to-air or Pay TV.  Watch live sport on TV tonight."
    
  end
end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
  
  before_filter :authenticate
  
  # GET /rules
  # GET /rules.json
  def index
    @title = "Rules | Sport on Television in Australia"
    @breadcrumb = "Rules"
    @meta_keywords = "sport, television, tv, coverage, tonight, Australia, Melbourne, Sydney, Brisbane, Adalaide, Perth"
    @meta_description = "Your source for sport on television in Australia.  Find out when sport is on Free-to-air or Pay TV.  Watch live sport on TV tonight."
    @meta_author = "contact@sportontv.com.au"
    @regions = Region.all
        
    # fetching a single feed
    feed_uri = "http://au.news.search.yahoo.com/news/rss?p=sport"
    news_feed = Feedzirra::Feed.fetch_and_parse(feed_uri)
    @news_entries = news_feed.entries  
    
    
    #get the rules sorted aligned to the algorithm
    querystring = "
    SELECT id, rule_type, priority, value, sport_name, created_at, updated_at, channel_xmltv_id, LENGTH(value) AS value_length, DATE(updated_at) = DATE(NOW()) AS updated_today
    FROM rules
    ORDER BY rule_type, priority DESC, value_length DESC
    "    
    @rules = Rule.find_by_sql(querystring)
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rules }
    end
  end

  # GET /rules/1
  # GET /rules/1.json
  def show
    @rule = Rule.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rule }
    end
  end

  # GET /rules/new
  # GET /rules/new.json
  def new
    @rule = Rule.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rule }
    end
  end

  # GET /rules/1/edit
  def edit
    @rule = Rule.find(params[:id])
  end

  # POST /rules
  # POST /rules.json
  def create
    @rule = Rule.new(params[:rule])

    respond_to do |format|
      if @rule.save
        format.html { redirect_to @rule, notice: 'Rule was successfully created.' }
        format.json { render json: @rule, status: :created, location: @rule }
      else
        format.html { render action: "new" }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rules/1
  # PUT /rules/1.json
  def update
    @rule = Rule.find(params[:id])

    respond_to do |format|
      if @rule.update_attributes(params[:rule])
        format.html { redirect_to @rule, notice: 'Rule was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rules/1
  # DELETE /rules/1.json
  def destroy
    @rule = Rule.find(params[:id])
    @rule.destroy

    respond_to do |format|
      format.html { redirect_to rules_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  
  before_filter :authenticate
  
  # GET /sports/1
  # GET /sports/1.json
  def show
    @sport = Sport.find(params[:id])
    @regions = Region.all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sport }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def logged_in?
    not request.authorization.nil?
  end
    
  def google_analytics
    google_code ="
    <script>
    var _gaq=[['_setAccount','UA-00000000-1'],['_trackPageview']];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
    g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g,s)}(document,'script'));
    </script>"
       
    google_code
  end
  
  
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/log_entries_helper.rb
module LogEntriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/parameters_helper.rb
module ParametersHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/raw_channels_helper.rb
module RawChannelsHelper
end

app/helpers/raw_programs_helper.rb
module RawProgramsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/views/rules/_form.html.erb
<%= form_for(@rule) do |f| %>
  <% if @rule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rule.errors.count, "error") %> prohibited this rule from being saved:</h2>

      <ul>
      <% @rule.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rule_type %><br />
    <%= f.text_field :rule_type %>
  </div>
  <div class="field">
    <%= f.label :priority %><br />
    <%= f.number_field :priority %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.datetime_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.datetime_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :channel_id %><br />
    <%= f.number_field :channel_id %>
  </div>
  <div class="field">
    <%= f.label :channel_xmltv_id %><br />
    <%= f.text_field :channel_xmltv_id %>
  </div>
  <div class="field">
    <%= f.label :sport_id %><br />
    <%= f.number_field :sport_id %>
  </div>
  <div class="field">
    <%= f.label :sport_name %><br />
    <%= f.text_field :sport_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rules/edit.html.erb
<h1>Editing rule</h1>

<%= render 'form' %>

<%= link_to 'Show', @rule %> |
<%= link_to 'Back', rules_path %>

app/views/rules/index.html.erb
<h2>Rule Algorithm</h2>
<p>Rules are applied as follows:</p>
<p>1. Black Channels are all checked, no order required.</p>
<p>2. Black Keywords are all checked, no order required.</p>
<p>3. White Keywords are checked.  The keywords are ordered as follows:</p>
<pre>
  SELECT value, sport_name
  FROM rules
  WHERE rule_type = 'White Keyword'
  ORDER BY priority DESC, LENGTH(value) DESC
</pre>
<p>4. Then anything with a generic 'sport' match is included</p>
<p>5. Except anything containing 'weather' or 'news'</p>
<h2>Listing Rules</h2>
<p>Create a new rule: <%= link_to 'New', new_rule_path, :class => 'btn btn-mini btn-primary' %></p>
<table class="table table-striped table-condensed admin">
  <thead>
    <tr>
      <th>Type</th>
      <th>Priority</th>
      <th>Rule</th>
      <th>Sport</th>
      <th>Actions</th>
    </tr> 
  </thead>
  <tbody>
    <% @rules.each do |rule| %>
      <% if rule.updated_today %>
      <tr class="success">
      <% else %>
      <tr>
      <% end %>
        <td><%= rule.rule_type %></td>
        <td><%= rule.priority %></td>
        <td><%= link_to rule.value, rule_path(rule.id) %></td>
        <td><%= rule.sport_name %></td>
        <td>
          <%= link_to 'Edit', edit_rule_path(rule), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', rule, confirm: 'Are you sure?', method: :delete, :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/rules/new.html.erb
<h1>New rule</h1>

<%= render 'form' %>

<%= link_to 'Back', rules_path %>

app/views/rules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Rule type:</b>
  <%= @rule.rule_type %>
</p>

<p>
  <b>Priority:</b>
  <%= @rule.priority %>
</p>

<p>
  <b>Value:</b>
  <%= @rule.value %>
</p>

<p>
  <b>Start date:</b>
  <%= @rule.start_date %>
</p>

<p>
  <b>End date:</b>
  <%= @rule.end_date %>
</p>

<p>
  <b>Channel:</b>
  <%= @rule.channel_id %>
</p>

<p>
  <b>Channel xmltv:</b>
  <%= @rule.channel_xmltv_id %>
</p>

<p>
  <b>Sport:</b>
  <%= @rule.sport_id %>
</p>

<p>
  <b>Sport name:</b>
  <%= @rule.sport_name %>
</p>


<%= link_to 'Edit', edit_rule_path(@rule) %> |
<%= link_to 'Back', rules_path %>

app/views/sports/show.html.erb
<h2>Show Sport</h2>
<div class="well">
  <dl class="dl-horizontal">
    <dt>Sport name:</dt>
    <dd><%= @sport.sport_name %></dd>
  </dl>
</div>